[package]
name = "hello_rust"
version = "0.1.0"
authors = ["ndgndg91 <ndgndg91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "self_lib"
path = "src/lib/demo.rs"

[dependencies]
thiserror = "1.0"